# -*- coding: utf-8 -*-
"""clean table correspondance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtSw0SjdcZsx1KXJKI8Ck21wc201e7-8
"""

# librairies
import pandas as pd

df_correspondance = pd.read_csv('correspondance-code-insee-code-postal.csv', sep = ';')

df_correspondance.head()

# split code postal

# Duplication des lignes en éclatant les codes postaux
df_exploded = df_correspondance.assign(**{"Code Postal": df_correspondance["Code Postal"].str.split("/")}).explode("Code Postal")

# split geo_point_2D
df_exploded['latitude'] = df_exploded["geo_point_2d"].str.split(",").str[0]
df_exploded['longitude'] = df_exploded["geo_point_2d"].astype(str).str.split(",", n=1).str[1]

df_exploded

# Mettre à jour les codes postaux en fonction de 2019
df_exploded.loc[df_exploded['Commune'] == 'LEGE-CAP-FERRET', 'Code postal'] = 33970
df_exploded.loc[df_exploded['Commune'] == 'LEGE-CAP-FERRET', 'Code postal'] = 33970



LEGE-CAP-FERRET: 33970

ZONZA :20144

SAINT-PAUL : 97411

COGGIA : 20118

SAINT-LOUIS : 97421

SAINT-PAUL : 97422

VICO : 20118

LA TESTE-DE-BUCH : 33115

SAINT-PAUL : 97435
3
23
SAINT-PAUL
97423
2
24
CONCA
20144
2
25
MARTIGUES
13117
2
26
NANCY
54100
2
27
ARLES
13129
1
28
SABLES-D'OLONNE (LES)
nan
1
29
ARLES
13280
1
30
LE TAMPON
97418
1

# enregistrer en csv
df_exploded.to_csv("correspondance_code_postal_insee.csv")